kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azureblob-nfs-premium-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
parameters:
  protocol: nfs
  skuName: Premium_LRS
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
