apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  creationTimestamp: "2024-10-23T16:26:48Z"
  generation: 3
  labels:
    argocd.argoproj.io/instance: xyz-service
  name: xyz-service
  namespace: xyz
  resourceVersion: "69708860"
  uid: 45817b7a-de64-4c69-a39a-9c85527e76c7
spec:
  parameters:
    clientID: 0000000-0000-0000-0000-000000000000 //Manage Identity Client ID
    keyvaultName: kv-prod01
    objects: |
      array:
        - |
          objectName: DbServerName
          objectType: secret
        - |
          objectName: DbPassword
          objectType: secret
        - |
          objectName: DbUserName
          objectType: secret
    tenantId: 0000000-0000-0000-0000-000000000000 //Manage Identity Tenant ID
    usePodIdentity: "false"
  provider: azure
  secretObjects:
  - data:
    - key: DB_HOST
      objectName: DbServerName
    - key: DB_PASSWORD
      objectName: DbPassword
    - key: DB_USER
      objectName: DbUserName
    labels:
      app.kubernetes.io/instance: xyz-service
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: xyz-service
      app.kubernetes.io/version: 0.0.1
      helm.sh/chart: xyz-service-0.1.0
    secretName: xyz-service
    type: Opaque
