apiVersion: apps/v1
kind: Deployment
metadata:
  name: required-for-kustomize-but-not-used
  namespace: flux-system
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"