apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: serviceaccount-workload-identity-patch.yaml
  target:
    kind: ServiceAccount
    namespace: flux-system
    name: source-controller
- path: deployment-flux-use-workload-idenity.yaml
  target:
    kind: Deployment
    namespace: flux-system
    name: source-controller
