apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
# Option 1: Inline patch example (can be removed if going with path-based patches)
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: source-controller
      namespace: flux-system
      annotations:
        azure.workload.identity/client-id: ad1f41f3-6dbd-4395-bb69-be360542d124
        azure.workload.identity/tenant-id: 4c83ec3e-26b4-444f-afb7-8b171cd1b420
      labels:
        azure.workload.identity/use: "true"
  target:
    kind: ServiceAccount
    namespace: flux-system


- path: deployment-flux-use-workload-idenity.yaml
  target:
    kind: Deployment
    namespace: flux-system
    name: source-controller
