metadata:
  annotations:
    azure.workload.identity/client-id: ad1f41f3-6dbd-4395-bb69-be360542d124
    azure.workload.identity/tenant-id: 4c83ec3e-26b4-444f-afb7-8b171cd1b420
  labels:
    azure.workload.identity/use: "true"
