apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-nfs-premium-compatible
provisioner: blob.csi.azure.com
parameters:
  protocol: nfs
  skuName: Premium_LRS
mountOptions:
  - sec=sys
  - nolock
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true 